Fix documentation and example's package.json
fingerprintjs/fingerprintjs-pro-react pull request #5
Opened 2022-03-09 06:05 UTC by sshelomentsev

2022-03-11 07:31 UTC, borislobanov92 requested changes

2022-03-11 07:31 UTC, borislobanov92 commented on examples/spa/package.json
> +    "@fingerprintjs/fingerprintjs-pro-react": "file:../../",
@sshelomentsev did the `link` approach not work for you? And did the `file` approach work?

2022-03-11 07:31 UTC, borislobanov92 commented on README.md
> +      region: 'selected region'
This is not a required field, by default this will be `us` which is the absolute majority of our subscriptions.

2022-03-11 07:31 UTC, borislobanov92 commented on README.md
> +import React, { useState } from 'react';
👍

2022-03-11 08:27 UTC, sshelomentsev commented on examples/spa/package.json
> +    "@fingerprintjs/fingerprintjs-pro-react": "file:../../",
`link` is not supported by npm. `file` supported by both `npm` and `yarn`.

2022-03-11 08:33 UTC, sshelomentsev commented on README.md
> +      region: 'selected region'
Ok, might be it's enough to have note for users from EU/Asia in the quick start [guide](https://dev.fingerprintjs.com/docs/quick-start-guide) of the library.

2022-04-08 10:43 UTC, ilfa approved these changes

2022-04-08 10:45 UTC, borislobanov92 approved these changes

2022-04-08 13:52 UTC, merged